Repository Challenge-Hanbang-E/Hanbang-E_Page, pull requests merged in 2023-01, with the labels that each got.

#5 ✨Feat: 주문 상세 페이지 레이아웃
  .gitignore
  static/img/logo.png
  templates/order_details.html
Labels: feature

#7 [feat] 메인 페이지 추가
  templates/index.html
Labels: feature

#8 ✨Feat : 상품검색 페이지 추가
  static/img/product1.jpeg
  templates/index.html
  templates/product_search.html
Labels: feature

#10 ✨ Feat: 주문 상세 페이지 API 연동 및 css 수정
  templates/order_details.html
Labels: feature

#13 ✨ Feat: 상품 상세조회 페이지 API연결
  templates/product-detail.html
Labels: feature

#16 ✨ Feat : 회원가입 페이지 API 연동
  templates/signup.html
Labels: feature

#18 ✨ Feat : 메인 페이지 API 연동
  static/img/order_details.png
  templates/index.html
  templates/product_search.html
Labels: feature

#20 🔨️ Refactor : 전체 페이지 코드 정리 및 CSS 수정
  templates/index.html
  templates/order_details.html
  templates/product-detail.html
Labels: refactor

#22 🔨️ Refactor : 전체 페이지 코드 정리 및 CSS 추가 수정
  templates/index.html
  templates/product-detail.html
Labels: refactor

#26 🐛 Fix: 배포시 이미지 경로 문제 해결
  index.html
  login.html
  order_details.html
  product-detail.html
  signup.html
Labels: fix

#28 🔨️ Refactor: 로그인, 회원가입 페이지와 메인페이지 연결
  login.html
  signup.html
Labels: refactor

#30 ✨ Feat : JWT를 통한 회원 인증/인가 기능 추가
  index.html
  login.html
  order_details.html
  product-detail.html
Labels: feature

#34 🔨️ Refactor : 메인 페이지 css
  index.html
Labels: refactor

#38 [feat] 예외상황 발생 시 Alert기능 추가
  index.html
  login.html
  order_details.html
  product-detail.html
Labels: enhancement
